"""Initial migration

Revision ID: f834eaa16412
Revises: 
Create Date: 2025-10-24 22:52:40.780093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f834eaa16412'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_files_quiz_id', table_name='files')
    op.drop_index('idx_files_user_id', table_name='files')
    op.create_index(op.f('ix_files_quiz_id'), 'files', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_files_user_id'), 'files', ['user_id'], unique=False)
    op.drop_table_comment(
        'files',
        existing_comment='Таблица метаданных загруженных файлов',
        schema=None
    )
    op.alter_column('quizzes', 'structure',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment=None,
               existing_comment='JSONB структура опроса: вопросы, типы, логика переходов',
               existing_nullable=False)
    op.alter_column('quizzes', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment=None,
               existing_comment='JSONB настройки: онбординг, брендирование',
               existing_nullable=False)
    op.alter_column('quizzes', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_quizzes_creator_id', table_name='quizzes')
    op.drop_index('idx_quizzes_status', table_name='quizzes')
    op.drop_index('idx_quizzes_structure', table_name='quizzes', postgresql_using='gin')
    op.create_index(op.f('ix_quizzes_creator_id'), 'quizzes', ['creator_id'], unique=False)
    op.create_index(op.f('ix_quizzes_status'), 'quizzes', ['status'], unique=False)
    op.drop_table_comment(
        'quizzes',
        existing_comment='Таблица опросов с JSONB структурой',
        schema=None
    )
    op.alter_column('responses', 'answers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment=None,
               existing_comment='JSONB ответы пользователя на все вопросы',
               existing_nullable=False)
    op.drop_index('idx_responses_answers', table_name='responses', postgresql_using='gin')
    op.drop_index('idx_responses_quiz_id', table_name='responses')
    op.drop_index('idx_responses_user_id', table_name='responses')
    op.drop_constraint('responses_quiz_id_user_id_key', 'responses', type_='unique')
    op.create_index(op.f('ix_responses_quiz_id'), 'responses', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_responses_user_id'), 'responses', ['user_id'], unique=False)
    op.drop_table_comment(
        'responses',
        existing_comment='Таблица ответов пользователей на опросы',
        schema=None
    )
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_users_is_admin', table_name='users')
    op.drop_index('idx_users_telegram_id', table_name='users')
    op.drop_constraint('users_telegram_id_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_is_admin'), 'users', ['is_admin'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.drop_table_comment(
        'users',
        existing_comment='Таблица пользователей бота',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        'Таблица пользователей бота',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_admin'), table_name='users')
    op.create_unique_constraint('users_telegram_id_key', 'users', ['telegram_id'])
    op.create_index('idx_users_telegram_id', 'users', ['telegram_id'], unique=False)
    op.create_index('idx_users_is_admin', 'users', ['is_admin'], unique=False)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.create_table_comment(
        'responses',
        'Таблица ответов пользователей на опросы',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_responses_user_id'), table_name='responses')
    op.drop_index(op.f('ix_responses_quiz_id'), table_name='responses')
    op.create_unique_constraint('responses_quiz_id_user_id_key', 'responses', ['quiz_id', 'user_id'])
    op.create_index('idx_responses_user_id', 'responses', ['user_id'], unique=False)
    op.create_index('idx_responses_quiz_id', 'responses', ['quiz_id'], unique=False)
    op.create_index('idx_responses_answers', 'responses', ['answers'], unique=False, postgresql_using='gin')
    op.alter_column('responses', 'answers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               comment='JSONB ответы пользователя на все вопросы',
               existing_nullable=False)
    op.create_table_comment(
        'quizzes',
        'Таблица опросов с JSONB структурой',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_quizzes_status'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_creator_id'), table_name='quizzes')
    op.create_index('idx_quizzes_structure', 'quizzes', ['structure'], unique=False, postgresql_using='gin')
    op.create_index('idx_quizzes_status', 'quizzes', ['status'], unique=False)
    op.create_index('idx_quizzes_creator_id', 'quizzes', ['creator_id'], unique=False)
    op.alter_column('quizzes', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'draft'::character varying"),
               existing_nullable=False)
    op.alter_column('quizzes', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               comment='JSONB настройки: онбординг, брендирование',
               existing_nullable=False)
    op.alter_column('quizzes', 'structure',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               comment='JSONB структура опроса: вопросы, типы, логика переходов',
               existing_nullable=False)
    op.create_table_comment(
        'files',
        'Таблица метаданных загруженных файлов',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_files_user_id'), table_name='files')
    op.drop_index(op.f('ix_files_quiz_id'), table_name='files')
    op.create_index('idx_files_user_id', 'files', ['user_id'], unique=False)
    op.create_index('idx_files_quiz_id', 'files', ['quiz_id'], unique=False)
    # ### end Alembic commands ###
